name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check-build:
    runs-on: ubuntu-latest
    container:
      image: jamieleecho/coco-dev:0.81
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Check compile
        run: |
          make tests
